### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by linkjek** [504250439/second-hand-bbs#1]
楼主能给个联系方式吗遇到了一些问题想请教一下

**Comment by codeErrorSleep** [comment]
可以的,加qq吧,504250439




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "504250439/second-hand-bbs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 上午10:53
收件人:&nbsp;"504250439/second-hand-bbs"<second-hand-bbs@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[504250439/second-hand-bbs] 求助 (#1)





 
楼主能给个联系方式吗遇到了一些问题想请教一下
