### ISSUE TITLE
项目无图片

### ISSUE THREAD

**Issue by luzhao260** [504250439/second-hand-bbs#2]
兄die，no picture material in project

**Comment by codeErrorSleep** [comment]
&nbsp; 你好,图片是存在本地的,你可以通过发布功能去上传新的物品图片,这样就有图片了.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "504250439/second-hand-bbs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月6日(星期六) 晚上6:08
收件人:&nbsp;"504250439/second-hand-bbs"<second-hand-bbs@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[504250439/second-hand-bbs] 项目无图片 (#2)





 
兄die，no picture material in project

**Comment by luzhao260** [comment]
我原是打算看你项目演示里的图片的。这么说的话，那我自己上传一下。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "504250439/second-hand-bbs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月10日(星期三) 中午11:08
收件人:&nbsp;"504250439/second-hand-bbs"<second-hand-bbs@noreply.github.com&gt;;
抄送:&nbsp;"向上仰望"<2606292175@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [504250439/second-hand-bbs] 项目无图片 (#2)





 &amp;nbsp; 你好,图片是存在本地的,你可以通过发布功能去上传新的物品图片,这样就有图片了. 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "504250439/second-hand-bbs"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2021年2月6日(星期六) 晚上6:08 
 收件人:&amp;nbsp;"504250439/second-hand-bbs"<second-hand-bbs@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[504250439/second-hand-bbs] 项目无图片 (#2) 
 
 
 
 
 
   
 兄die，no picture material in project
